/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MyType, MyType2 } from "./components/my-component/my-component";
export { MyType, MyType2 } from "./components/my-component/my-component";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
export interface MyComponentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMyComponentElement;
}
declare global {
    interface HTMLMyComponentElementEventMap {
        "myAnyEvent": any;
        "myStringEvent": string;
        "myNumberEvent": number;
        "myBooleanEvent": boolean;
        "myUnknownEvent": unknown;
        "myVoidEvent": void;
        "myUndefinedEvent": undefined;
        "myNullEvent": null;
        "myObjectEvent": { foo: string };
        "myDateEvent": Date;
        "myNestedDateEvent": { date: Date };
        "myTypeEvent": MyType;
        "myType2Event": MyType2;
        "myArrayEvent": Array<string>;
        "myArrayEvent2": string[];
    }
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMyComponentElementEventMap>(type: K, listener: (this: HTMLMyComponentElement, ev: MyComponentCustomEvent<HTMLMyComponentElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMyComponentElementEventMap>(type: K, listener: (this: HTMLMyComponentElement, ev: MyComponentCustomEvent<HTMLMyComponentElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
        "onMyAnyEvent"?: (event: MyComponentCustomEvent<any>) => void;
        "onMyArrayEvent"?: (event: MyComponentCustomEvent<Array<string>>) => void;
        "onMyArrayEvent2"?: (event: MyComponentCustomEvent<string[]>) => void;
        "onMyBooleanEvent"?: (event: MyComponentCustomEvent<boolean>) => void;
        "onMyDateEvent"?: (event: MyComponentCustomEvent<Date>) => void;
        "onMyNestedDateEvent"?: (event: MyComponentCustomEvent<{ date: Date }>) => void;
        "onMyNullEvent"?: (event: MyComponentCustomEvent<null>) => void;
        "onMyNumberEvent"?: (event: MyComponentCustomEvent<number>) => void;
        "onMyObjectEvent"?: (event: MyComponentCustomEvent<{ foo: string }>) => void;
        "onMyStringEvent"?: (event: MyComponentCustomEvent<string>) => void;
        "onMyType2Event"?: (event: MyComponentCustomEvent<MyType2>) => void;
        "onMyTypeEvent"?: (event: MyComponentCustomEvent<MyType>) => void;
        "onMyUndefinedEvent"?: (event: MyComponentCustomEvent<undefined>) => void;
        "onMyUnknownEvent"?: (event: MyComponentCustomEvent<unknown>) => void;
        "onMyVoidEvent"?: (event: MyComponentCustomEvent<void>) => void;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
