'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import { type MyComponentCustomEvent, type MyType, type MyType2 } from "stencil-foo-core";
import { MyComponent as MyComponentElement, defineCustomElement as defineMyComponent } from "stencil-foo-core/dist/components/my-component.js";

export type MyComponentEvents = {
    onMyAnyEvent: EventName<CustomEvent<any>>,
    onMyStringEvent: EventName<CustomEvent<string>>,
    onMyNumberEvent: EventName<CustomEvent<number>>,
    onMyBooleanEvent: EventName<CustomEvent<boolean>>,
    onMyUnknownEvent: EventName<CustomEvent<unknown>>,
    onMyVoidEvent: EventName<CustomEvent<void>>,
    onMyUndefinedEvent: EventName<CustomEvent<undefined>>,
    onMyNullEvent: EventName<CustomEvent<null>>,
    onMyObjectEvent: EventName<CustomEvent<{ foo: string }>>,
    onMyDateEvent: EventName<MyComponentCustomEvent<Date>>,
    onMyNestedDateEvent: EventName<MyComponentCustomEvent<{ date: Date }>>,
    onMyTypeEvent: EventName<MyComponentCustomEvent<MyType>>,
    onMyType2Event: EventName<MyComponentCustomEvent<MyType2>>,
    onMyArrayEvent: EventName<MyComponentCustomEvent<Array<string>>>,
    onMyArrayEvent2: EventName<CustomEvent<string[]>>
};

export const MyComponent: StencilReactComponent<MyComponentElement, MyComponentEvents> = /*@__PURE__*/ createComponent<MyComponentElement, MyComponentEvents>({
    tagName: 'my-component',
    elementClass: MyComponentElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMyAnyEvent: 'myAnyEvent',
        onMyStringEvent: 'myStringEvent',
        onMyNumberEvent: 'myNumberEvent',
        onMyBooleanEvent: 'myBooleanEvent',
        onMyUnknownEvent: 'myUnknownEvent',
        onMyVoidEvent: 'myVoidEvent',
        onMyUndefinedEvent: 'myUndefinedEvent',
        onMyNullEvent: 'myNullEvent',
        onMyObjectEvent: 'myObjectEvent',
        onMyDateEvent: 'myDateEvent',
        onMyNestedDateEvent: 'myNestedDateEvent',
        onMyTypeEvent: 'myTypeEvent',
        onMyType2Event: 'myType2Event',
        onMyArrayEvent: 'myArrayEvent',
        onMyArrayEvent2: 'myArrayEvent2'
    } as MyComponentEvents,
    defineCustomElement: defineMyComponent
});
